name: Keep Streamlit App Awake

on:
  schedule:
    # Runs every 4 hours (At minute 0 past every 4th hour)
    - cron: '0 */4 * * *'
  workflow_dispatch: # Allows you to trigger this manually whenever you want

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit App
        run: |
          curl -I "https://atomapp-mszkbilamwthrtksvhvm8a.streamlit.app/"
